export const DOMAIN = "http://localhost:3001/student";
export const limit = 5;
// HTTP method 
export const HTTP_READ = "GET"
export const HTTP_CREATE = "POST"
export const HTTP_UPDATE = "PUT"
export const HTTP_DELETE = "DELETE"

// HTTP headers
export const HTTP_HEADER_JSON = {"Content-Type": "Application/json"}

export const GET_LIST_STUDENT_REQUEST = 'GET_LIST_STUDENT_REQUEST'
export const GET_LIST_STUDENT_SUCCESS = 'GET_LIST_STUDENT_SUCCESS'
export const GET_LIST_STUDENT_FAILURE = 'GET_LIST_STUDENT_FAILURE'

export const ADD_LIST_STUDENT_REQUEST = 'ADD_LIST_STUDENT_REQUEST'
export const ADD_LIST_STUDENT_SUCCESS = 'ADD_LIST_STUDENT_SUCCESS'
export const ADD_LIST_STUDENT_FAILURE = 'ADD_LIST_STUDENT_FAILURE'

export const DELETE_LIST_STUDENT_REQUEST = 'DELETE_LIST_STUDENT_REQUEST'
export const DELETE_LIST_STUDENT_SUCCESS = 'DELETE_LIST_STUDENT_SUCCESS'
export const DELETE_LIST_STUDENT_FAILURE = 'DELETE_LIST_STUDENT_FAILURE'

export const UPDATE_LIST_STUDENT_REQUEST = 'UPDATE_LIST_STUDENT_REQUEST'
export const UPDATE_LIST_STUDENT_SUCCESS = 'UPDATE_LIST_STUDENT_SUCCESS'
export const UPDATE_LIST_STUDENT_FAILURE = 'UPDATE_LIST_STUDENT_FAILURE'

export const PAGINATION_LIST_STUDENT_REQUEST = 'PAGINATION_LIST_STUDENT_REQUEST'
export const PAGINATION_LIST_STUDENT_SUCCESS = 'PAGINATION_LIST_STUDENT_SUCCESS'
export const PAGINATION_LIST_STUDENT_FAILURE = 'PAGINATION_LIST_STUDENT_FAILURE'

export const SEARCH_LIST_STUDENT_REQUEST = 'SEARCH_LIST_STUDENT_REQUEST'
export const SEARCH_LIST_STUDENT_SUCCESS = 'SEARCH_LIST_STUDENT_SUCCESS'
export const SEARCH_LIST_STUDENT_FAILURE = 'SEARCH_LIST_STUDENT_FAILURE'

export const CLEAN_EFFECT = 'CLEAN_EFFECT'